# Default xacro arguments for the Forki3 sensors1 model.
# Runtime arguments such as namespace, robot_name, and sim_file are provided by launch files.

body_use_inertial: "True"
mass: "500"
body_size: "1.531 0.774 1.64"
ballast_size_z: "0.1"
body_ground_clearance: "0.06"
dist_to_wheels: "0.50"
alpha_deg: "154"
body_mesh: "robot_forki3/meshes/forklift_chassis.stl"
body_scale: "1.0 1.0 1.0"
body_color: "0.0 0.0 1.0 1.0"
s_wheel_use_inertial: "True"
s_wheel_mass: "10.0"
s_wheel_radius: "0.127"
s_wheel_thickness: "0.082"
s_wheel_color: "0.1 0.1 0.1 1.0"
s_wheel_steering_joint_limits: "-3.1416 3.1416 100.0 100000.0"
s_wheel_rotation_joint_limits: "100.0 100000.0"
fork_use_visual: "True"
fork_use_collision: "True"
fork_use_inertial: "False"
fork_use_v_mesh: "True"
fork_color: "0.1 0.1 0.1 1.0"
fork_use_c_mesh: "True"
fork_limits: "-0.005 0.8 0.2 20000.0"
fork_rest_clearance: "0.03"
fork_tine_open: "False"
top_platform_use_visual: "True"
top_platform_use_collision: "True"
top_platform_use_inertial: "True"
top_platform_color: "0.0 0.0 1.0 1.0"
front_top_lidar_use_visual: "True"
front_top_lidar_use_collision: "True"
front_top_lidar_use_inertial: "True"
front_top_lidar_use_v_mesh: "True"
front_top_lidar_v_mesh_use_low_res: "True"
front_top_lidar_color: ""
front_top_lidar_use_c_mesh: "False"
front_top_lidar_c_mesh_use_low_res: "True"
front_top_lidar_mount: "0.081809221 0 1.650260604 0 0.34906585 0"
back_top_lidar_use_visual: "True"
back_top_lidar_use_collision: "True"
back_top_lidar_use_inertial: "True"
back_top_lidar_use_v_mesh: "True"
back_top_lidar_v_mesh_use_low_res: "True"
back_top_lidar_color: "0 0 0 1"
back_top_lidar_use_c_mesh: "False"
back_top_lidar_c_mesh_use_low_res: "True"
back_top_lidar_mount: "-0.737309221 0 1.650260604 0 0.34906585 3.141592654"
back_bottom_lidar_use_visual: "True"
back_bottom_lidar_use_collision: "True"
back_bottom_lidar_use_inertial: "True"
back_bottom_lidar_use_v_mesh: "True"
back_bottom_lidar_v_mesh_use_low_res: "True"
back_bottom_lidar_color: "0 0 0 1"
back_bottom_lidar_use_c_mesh: "False"
back_bottom_lidar_c_mesh_use_low_res: "True"
back_bottom_lidar_mount: "-0.7025 0 0.292 3.141592654 0 3.141592654"
fork_rgbd_use_visual: "True"
fork_rgbd_use_collision: "True"
fork_rgbd_use_inertial: "True"
fork_rgbd_use_v_mesh: "True"
fork_rgbd_color: "0.5 0.5 0.5 1.0"
fork_rgbd_use_c_mesh: "False"
