/**/robot_state_publisher:
  ros__parameters:
    publish_frequency: 20.0
    ignore_timestamp: False # If True joint_state messages are accepted, no matter their timestamp
    # frame_prefix is not accepted
    # robot_description is set in the launch file

/**/three_swerve_kinematics:
  ros__parameters:
    # use_sim_time IS automatically handled, no need to specify here.

    initial_sw_states_reception_period: 10.0 # seconds to wait for the initial JointState seed.

    # Geometry is global and derived in C++ from dist_to_wheels and alpha_deg.
    steerable_wheels:
      radius: $(var st_wheel_radius)
      dist_to_wheels: $(var dist_to_wheels)
      alpha_deg: $(var alpha_deg)

      # Wheel numbering aligned with ground_vehicle_kinematics:
      # - steerable_wheel_1: wheel on the robot X axis, with x > 0 or x < 0 depending on geometry.
      # - steerable_wheel_2: left wheel.
      # - steerable_wheel_3: right wheel.
      # Reference:
      # package://ground_vehicle_kinematics/doc/kinematics_en.pdf

      steerable_wheel_1:
        name: "$(var robot_prefix)steerable_wheel_1"
        steerable_joint:
          name: "$(var robot_prefix)steerable_wheel_1_steerable_joint"
          # Note: If you want the wheel to be able to reach +-pi rad angle (+-180 degress), set limits to +-3.1416.
          # pi = 3.141592654.... < 3.1416
          limits: { lower: -3.1416, upper: 3.1416 } # rad
        rotation_joint:
          name: "$(var robot_prefix)steerable_wheel_1_rotation_joint"
          limits: { lower: -50.0, upper: 50.0 } # rad/s

      steerable_wheel_2:
        name: "$(var robot_prefix)steerable_wheel_2"
        steerable_joint:
          name: "$(var robot_prefix)steerable_wheel_2_steerable_joint"
          # Note: If you want the wheel to be able to reach +-pi rad angle (+-180 degress), set limits to +-3.1416.
          # pi = 3.141592654.... < 3.1416
          limits: { lower: -3.1416, upper: 3.1416 } # rad
        rotation_joint:
          name: "$(var robot_prefix)steerable_wheel_2_rotation_joint"
          limits: { lower: -50.0, upper: 50.0 } # rad/s

      steerable_wheel_3:
        name: "$(var robot_prefix)steerable_wheel_3"
        steerable_joint:
          name: "$(var robot_prefix)steerable_wheel_3_steerable_joint"
          # Note: If you want the wheel to be able to reach +-pi rad angle (+-180 degress), set limits to +-3.1416.
          # pi = 3.141592654.... < 3.1416
          limits: { lower: -3.1416, upper: 3.1416 } # rad
        rotation_joint:
          name: "$(var robot_prefix)steerable_wheel_3_rotation_joint"
          limits: { lower: -50.0, upper: 50.0 } # rad/s

/**/rosgz_bridge:
  ros__parameters:
    subscription_heartbeat: 1000
    # config_file, expand_gz_topic_names and override_timestamps_with_wall_time are forced in the launch file.
    # See the launch file 'rosgz_bridge.launch.py' for details.
