/**/three_swerve_kinematics:
  ros__parameters:
    # use_sim_time IS automatically handled, no need to specify here.

    kinematics_solver_type: "mixed" # direct: JointState->Twist, inverse: Twist->JointState, mixed: run both flows.
    inverse_kinematics_solver_initialization_timeout: 10.0 # seconds to wait for the initial JointState seed.

    # Most of the values found here can be obtained either from the file ./description.yaml or the file
    # ../urdf/description.xacro
    steerable_wheels:
      steerable_wheel_a:
        name: "front_steerable_wheel"
        radius: 0.127
        steerable_joint:
          name: "front_steerable_wheel_steerable_joint"
          parent_link_name: "base_link"
          child_link_name: "front_steerable_wheel_steerable_link"
          origin: { x: 0.46, y: 0.0, z: 0.067, R: 0.0, P: 0.0, Y: 0.0 }
          angular_limits: { lower: -3.14159, upper: 3.14159 } # Solver enforces continuity within these bounds.
        rotation_joint:
          name: "front_steerable_wheel_rotation_joint"
          parent_link_name: "front_steerable_wheel_steerable_link"
          child_link_name: "front_steerable_wheel_rotation_link"
          origin: { x: 0.0, y: 0.0, z: 0.0, R: 0.0, P: 0.0, Y: 0.0 }

      steerable_wheel_b:
        name: "rear_left_steerable_wheel"
        radius: 0.127
        steerable_joint:
          name: "rear_left_steerable_wheel_steerable_joint"
          parent_link_name: "base_link"
          child_link_name: "rear_left_steerable_wheel_steerable_link"
          origin: { x: -0.46, y: 0.219, z: 0.067, R: 0.0, P: 0.0, Y: 0.0 }
          angular_limits: { lower: -3.14159, upper: 3.14159 }
        rotation_joint:
          name: "rear_left_steerable_wheel_rotation_joint"
          parent_link_name: "rear_left_steerable_wheel_steerable_link"
          child_link_name: "rear_left_steerable_wheel_rotation_link"
          origin: { x: 0.0, y: 0.0, z: 0.0, R: 0.0, P: 0.0, Y: 0.0 }

      steerable_wheel_c:
        name: "rear_right_steerable_wheel"
        radius: 0.127
        steerable_joint:
          name: "rear_right_steerable_wheel_steerable_joint"
          parent_link_name: "base_link"
          child_link_name: "rear_right_steerable_wheel_steerable_link"
          origin: { x: -0.46, y: -0.219, z: 0.067, R: 0.0, P: 0.0, Y: 0.0 }
          angular_limits: { lower: -3.14159, upper: 3.14159 }
        rotation_joint:
          name: "rear_right_steerable_wheel_rotation_joint"
          parent_link_name: "rear_right_steerable_wheel_steerable_link"
          child_link_name: "rear_right_steerable_wheel_rotation_link"
          origin: { x: 0.0, y: 0.0, z: 0.0, R: 0.0, P: 0.0, Y: 0.0 }
